package ui;

import javax.swing.JLabel;

public class PageEmployeeData extends ui.base.AbstractProfilePage {

    public PageEmployeeData() {
        initComponents();

        // Initialize profile page
        initializeProfilePage();
    }

    // Implement all required methods:
    @Override public JLabel getEmployeeIDText()       { return employeeIDText;       }
    @Override public JLabel getPositionText()         { return positionText;         }
    @Override public JLabel getFirstNameText()        { return firstNameText;        }
    @Override public JLabel getLastNameText()         { return lastNameText;         }
    @Override public JLabel getBirthdayText()         { return birthdayText;         }
    @Override public JLabel getPhoneNumberText()      { return phoneNumberText;      }
    @Override public JLabel getAddressText()          { return addressText;          }
    @Override public JLabel getSupervisorText()       { return supervisorText;       }
    @Override public JLabel getStatusText()           { return statusText;           }
    @Override public JLabel getSSSNumberText()        { return sssNumberText;        }
    @Override public JLabel getPagibigNumberText()    { return pagibigNumberText;    }
    @Override public JLabel getPhilhealthNumberText() { return philhealthNumberText; }
    @Override public JLabel getTINNumberText()        { return tinNumberText;        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastNameText = new javax.swing.JLabel();
        firstNameText = new javax.swing.JLabel();
        birthdayText = new javax.swing.JLabel();
        phoneNumberText = new javax.swing.JLabel();
        addressText = new javax.swing.JLabel();
        sssNumberText = new javax.swing.JLabel();
        pagibigNumberText = new javax.swing.JLabel();
        philhealthNumberText = new javax.swing.JLabel();
        tinNumberText = new javax.swing.JLabel();
        statusText = new javax.swing.JLabel();
        employeeIDText = new javax.swing.JLabel();
        positionText = new javax.swing.JLabel();
        supervisorText = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        modifyCredentialsButton = new util.LightButton();
        editProfileButton = new util.LightButton();
        backButton = new util.LightButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastNameText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lastNameText.setForeground(new java.awt.Color(0, 102, 102));
        lastNameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lastNameText.setText("Last Name");
        getContentPane().add(lastNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 150, -1));

        firstNameText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        firstNameText.setForeground(new java.awt.Color(0, 102, 102));
        firstNameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firstNameText.setText("First Name");
        getContentPane().add(firstNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 150, -1));

        birthdayText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        birthdayText.setForeground(new java.awt.Color(0, 102, 102));
        birthdayText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        birthdayText.setText("Birthdate");
        getContentPane().add(birthdayText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 120, -1));

        phoneNumberText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        phoneNumberText.setForeground(new java.awt.Color(0, 102, 102));
        phoneNumberText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        phoneNumberText.setText("Phone Number");
        getContentPane().add(phoneNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 120, -1));

        addressText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addressText.setForeground(new java.awt.Color(0, 102, 102));
        addressText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressText.setText("Address");
        addressText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        addressText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addressText.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        addressText.setInheritsPopupMenu(false);
        getContentPane().add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 200, 90));

        sssNumberText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        sssNumberText.setForeground(new java.awt.Color(0, 102, 102));
        sssNumberText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sssNumberText.setText("SSS Number");
        getContentPane().add(sssNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 360, -1));

        pagibigNumberText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        pagibigNumberText.setForeground(new java.awt.Color(0, 102, 102));
        pagibigNumberText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pagibigNumberText.setText("Pag-Ibig Number");
        getContentPane().add(pagibigNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 360, -1));

        philhealthNumberText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        philhealthNumberText.setForeground(new java.awt.Color(0, 102, 102));
        philhealthNumberText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        philhealthNumberText.setText("Philhealth");
        getContentPane().add(philhealthNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 360, -1));

        tinNumberText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        tinNumberText.setForeground(new java.awt.Color(0, 102, 102));
        tinNumberText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tinNumberText.setText("TIN Number");
        getContentPane().add(tinNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 360, -1));

        statusText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        statusText.setForeground(new java.awt.Color(0, 102, 102));
        statusText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusText.setText("Status");
        getContentPane().add(statusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 360, -1));

        employeeIDText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        employeeIDText.setForeground(new java.awt.Color(0, 51, 51));
        employeeIDText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeIDText.setText("Employee ID");
        getContentPane().add(employeeIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 210, -1));

        positionText.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        positionText.setForeground(new java.awt.Color(0, 51, 51));
        positionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionText.setText("Position");
        getContentPane().add(positionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 210, -1));

        supervisorText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        supervisorText.setForeground(new java.awt.Color(0, 51, 51));
        supervisorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supervisorText.setText("Supervisor");
        getContentPane().add(supervisorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 210, -1));

        label12.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label12.setForeground(new java.awt.Color(0, 102, 102));
        label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label12.setText("Supervisor");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 210, -1));

        label11.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label11.setForeground(new java.awt.Color(0, 102, 102));
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setText("Position");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 210, -1));

        label10.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label10.setForeground(new java.awt.Color(0, 102, 102));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("Employee ID");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 210, -1));

        label9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 51, 51));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("First Name");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 210, -1));

        label8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(51, 51, 51));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label8.setText("Status");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 220, -1));

        label4.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(51, 51, 51));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("SSS Number");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 220, -1));

        label5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(51, 51, 51));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("Pag-Ibig Number");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 220, -1));

        label6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(51, 51, 51));
        label6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label6.setText("Philhealth");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 220, -1));

        label7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(51, 51, 51));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label7.setText("TIN Number");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 220, -1));

        label3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 51, 51));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("Address");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 200, -1));

        label2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 51));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("Phone Number");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 210, -1));

        label1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("Birthdate");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 210, -1));

        label.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(51, 51, 51));
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText("Surname");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 210, -1));

        modifyCredentialsButton.setForeground(new java.awt.Color(0, 102, 102));
        modifyCredentialsButton.setText("Modify Credentials");
        modifyCredentialsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyCredentialsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(modifyCredentialsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        editProfileButton.setForeground(new java.awt.Color(0, 102, 102));
        editProfileButton.setText("Edit Profile");
        editProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 130, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Profile.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Back to Employee Home
        new PageEmployeeHome().setVisible(true);
        this.dispose(); // Close current page
    }//GEN-LAST:event_backButtonActionPerformed

    private void modifyCredentialsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyCredentialsButtonActionPerformed
        // Open Modify Credentials page
        new PageEmployeeDataUpdateCredential().setVisible(true);
        this.dispose(); // Close current page
    }//GEN-LAST:event_modifyCredentialsButtonActionPerformed

    private void editProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileButtonActionPerformed
        // Open Edit Profile page
        new PageEmployeeDataUpdateProfile().setVisible(true);
        this.dispose(); // Close current page
    }//GEN-LAST:event_editProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageEmployeeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageEmployeeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageEmployeeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageEmployeeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageEmployeeData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel addressText;
    private util.LightButton backButton;
    private javax.swing.JLabel birthdayText;
    private util.LightButton editProfileButton;
    private javax.swing.JLabel employeeIDText;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lastNameText;
    private util.LightButton modifyCredentialsButton;
    private javax.swing.JLabel pagibigNumberText;
    private javax.swing.JLabel philhealthNumberText;
    private javax.swing.JLabel phoneNumberText;
    private javax.swing.JLabel positionText;
    private javax.swing.JLabel sssNumberText;
    private javax.swing.JLabel statusText;
    private javax.swing.JLabel supervisorText;
    private javax.swing.JLabel tinNumberText;
    // End of variables declaration//GEN-END:variables
}
