package ui;

public class PageFinancePayroll extends ui.base.AbstractPayrollPage {

    public PageFinancePayroll() {
        super();
        initComponents();

        setComponentReferences(
            payrollTable,
            JDateChooser,
            totalGrossField,
            totalContributionsField,
            totalDeductionsField,
            totalNetPayField
        );

        backButton.addActionListener(e -> {
            new PageFinanceHome().setVisible(true);
            this.dispose();
        });

        printPayrollButton.addActionListener(e -> {
            printPayrollReport(this);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label4 = new javax.swing.JLabel();
        totalNetPayField = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        totalDeductionsField = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        totalContributionsField = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        totalGrossField = new javax.swing.JTextField();
        backButton = new util.LightButton();
        printPayrollButton = new util.LightButton();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        payrollTable = new javax.swing.JTable();
        label2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setFont(new java.awt.Font("Inter", 3, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(51, 51, 51));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("TOTAL NET PAY");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 210, 30));

        totalNetPayField.setEditable(false);
        totalNetPayField.setBackground(new java.awt.Color(204, 204, 204));
        totalNetPayField.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        totalNetPayField.setForeground(new java.awt.Color(0, 102, 102));
        totalNetPayField.setText("0");
        getContentPane().add(totalNetPayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 240, 40));

        label3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 51, 51));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("TOTAL DEDUCTIONS");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 200, 30));

        totalDeductionsField.setEditable(false);
        totalDeductionsField.setBackground(new java.awt.Color(204, 204, 204));
        totalDeductionsField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        totalDeductionsField.setForeground(new java.awt.Color(0, 102, 102));
        totalDeductionsField.setText("0");
        getContentPane().add(totalDeductionsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 200, 30));

        label1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("TOTAL CONTRIBUTIONS");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 200, 30));

        totalContributionsField.setEditable(false);
        totalContributionsField.setBackground(new java.awt.Color(204, 204, 204));
        totalContributionsField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        totalContributionsField.setForeground(new java.awt.Color(0, 102, 102));
        totalContributionsField.setText("0");
        getContentPane().add(totalContributionsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 200, 30));

        label.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label.setForeground(new java.awt.Color(51, 51, 51));
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText("TOTAL GROSS EARNINGS");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 190, 30));

        totalGrossField.setEditable(false);
        totalGrossField.setBackground(new java.awt.Color(204, 204, 204));
        totalGrossField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        totalGrossField.setForeground(new java.awt.Color(0, 102, 102));
        totalGrossField.setText("0");
        getContentPane().add(totalGrossField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 190, 30));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        printPayrollButton.setForeground(new java.awt.Color(0, 102, 102));
        printPayrollButton.setText("Print Payroll");
        printPayrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printPayrollButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printPayrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 160, -1));

        JDateChooser.setForeground(new java.awt.Color(0, 102, 102));
        JDateChooser.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        getContentPane().add(JDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 130, 30));

        payrollTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        payrollTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(payrollTable);
        if (payrollTable.getColumnModel().getColumnCount() > 0) {
            payrollTable.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 940, 300));

        label2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 51));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("Filter by Date:");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 110, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/PayrollSummary.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void printPayrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPayrollButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printPayrollButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageFinancePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageFinancePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageFinancePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageFinancePayroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageFinancePayroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser JDateChooser;
    public util.LightButton backButton;
    private javax.swing.JLabel background;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    public javax.swing.JTable payrollTable;
    public util.LightButton printPayrollButton;
    public javax.swing.JTextField totalContributionsField;
    public javax.swing.JTextField totalDeductionsField;
    public javax.swing.JTextField totalGrossField;
    public javax.swing.JTextField totalNetPayField;
    // End of variables declaration//GEN-END:variables
}
