package ui;

public class PageManagerOvertimeAdmin extends ui.base.AbstractOvertimeAdminPage {

    public PageManagerOvertimeAdmin() {
        initComponents();

        // Connect all UI components to the abstract logic
        setComponentReferences(
            overtimeTable,
            employeeIDComboBox,
            JDateChooser
        );

        // Wire up the Refresh button to reload and reset all data and filters
        refreshButton.addActionListener(evt -> refreshAllData());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshButton = new util.BlueButton();
        employeeIDComboBox = new javax.swing.JComboBox<>();
        label10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overtimeTable = new javax.swing.JTable();
        viewOwnRecordButton = new util.LightButton();
        backButton = new util.LightButton();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        label8 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refreshButton.setForeground(new java.awt.Color(0, 102, 102));
        refreshButton.setText("Refresh Table");
        getContentPane().add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 160, -1));

        employeeIDComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        employeeIDComboBox.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(employeeIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 130, 30));

        label10.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(51, 51, 51));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label10.setText("   Find by ID:");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 100, 30));

        overtimeTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        overtimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(overtimeTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 940, 400));

        viewOwnRecordButton.setForeground(new java.awt.Color(0, 102, 102));
        viewOwnRecordButton.setText("View Own Record");
        viewOwnRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOwnRecordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewOwnRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 220, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        JDateChooser.setForeground(new java.awt.Color(0, 102, 102));
        JDateChooser.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        getContentPane().add(JDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 130, 30));

        label8.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(51, 51, 51));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label8.setText("Filter by Date:");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 110, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/AdminOvertimeRecords.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewOwnRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOwnRecordButtonActionPerformed
        new PageManagerOvertime().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewOwnRecordButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new PageManagerHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageManagerOvertimeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageManagerOvertimeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageManagerOvertimeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageManagerOvertimeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageManagerOvertimeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateChooser;
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> employeeIDComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label8;
    private javax.swing.JTable overtimeTable;
    private util.BlueButton refreshButton;
    private util.LightButton viewOwnRecordButton;
    // End of variables declaration//GEN-END:variables
}
