package ui;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import util.SessionManager;

public class PageHRHome extends ui.base.AbstractHomePage {

    public PageHRHome() {
        initComponents();

        // wire clock in/out → base methods
        clockInButton .addActionListener(e -> performClockIn());
        clockOutButton.addActionListener(e -> performClockOut());

        // wire logout → base helper
        initLogoutButton(logoutButton);

        // launch
        if (SessionManager.getUserID() != null
         && SessionManager.getEmployeeID() != 0) {
            SwingUtilities.invokeLater(() ->
                initializeHomePage(
                    SessionManager.getUserID(),
                    SessionManager.getEmployeeID()
                )
            );
        } else {
            JOptionPane.showMessageDialog(
                this, "No active session. Please login first."
            );
            new PageLogin().setVisible(true);
            dispose();
        }
    }

    // --- implement the abstract click action ---
    @Override
    protected void onProfileLabelClick() {
        new PageHREmployeeData().setVisible(true);
        dispose();
    }

    // --- delegate getters to your components ---
    @Override protected JLabel  getFullNameText()         { return fullNameText;         }
    @Override protected JLabel  getPositionText()         { return positionText;         }
    @Override protected JLabel  getDateTimeText()         { return dateTimeText;         }
    @Override protected JLabel  getClockInText()          { return clockInText;          }
    @Override protected JLabel  getClockOutText()         { return clockOutText;         }
    @Override protected JButton getClockInButton()        { return clockInButton;        }
    @Override protected JButton getClockOutButton()       { return clockOutButton;       }
    @Override protected JLabel  getTotalWorkedHoursText() { return totalWorkedHoursText; }
    @Override protected JLabel  getLeavesAvailableText()  { return leavesAvailableText;  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalWorkedHoursText = new javax.swing.JLabel();
        fullNameText = new javax.swing.JLabel();
        positionText = new javax.swing.JLabel();
        dateTimeText = new javax.swing.JLabel();
        inLabel = new javax.swing.JLabel();
        outLabel = new javax.swing.JLabel();
        clockInText = new javax.swing.JLabel();
        clockOutText = new javax.swing.JLabel();
        clockInButton = new util.BlueButton();
        clockOutButton = new util.BlueButton();
        leavesAvailableText = new javax.swing.JLabel();
        employeeDataButton = new util.BlueButton();
        attendanceButton = new util.BlueButton();
        payslipButton = new util.BlueButton();
        leaveButton = new util.BlueButton();
        overtimeButton = new util.BlueButton();
        logoutButton = new util.LightButton();
        payrollButton = new util.BlueButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalWorkedHoursText.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        totalWorkedHoursText.setForeground(new java.awt.Color(0, 153, 153));
        totalWorkedHoursText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        totalWorkedHoursText.setText("0");
        getContentPane().add(totalWorkedHoursText, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 220, -1));

        fullNameText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullNameText.setForeground(new java.awt.Color(0, 102, 102));
        fullNameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullNameText.setText("Employee");
        getContentPane().add(fullNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 190, 30));

        positionText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        positionText.setForeground(new java.awt.Color(0, 102, 102));
        positionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionText.setText("Position");
        getContentPane().add(positionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, -1));

        dateTimeText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        dateTimeText.setForeground(new java.awt.Color(0, 102, 102));
        dateTimeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTimeText.setText("Date & Time Here");
        getContentPane().add(dateTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 690, 80));

        inLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inLabel.setForeground(new java.awt.Color(0, 102, 102));
        inLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inLabel.setText("IN");
        getContentPane().add(inLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 180, -1));

        outLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        outLabel.setForeground(new java.awt.Color(0, 102, 102));
        outLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outLabel.setText("OUT");
        getContentPane().add(outLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 180, -1));

        clockInText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clockInText.setForeground(new java.awt.Color(0, 102, 102));
        clockInText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockInText.setText("-- : --");
        getContentPane().add(clockInText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 180, -1));

        clockOutText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clockOutText.setForeground(new java.awt.Color(0, 102, 102));
        clockOutText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clockOutText.setText("-- : --");
        getContentPane().add(clockOutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 180, -1));

        clockInButton.setForeground(new java.awt.Color(0, 102, 102));
        clockInButton.setText("Clock-In");
        getContentPane().add(clockInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 180, -1));

        clockOutButton.setForeground(new java.awt.Color(0, 102, 102));
        clockOutButton.setText("Clock-Out");
        getContentPane().add(clockOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 180, -1));

        leavesAvailableText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        leavesAvailableText.setForeground(new java.awt.Color(0, 153, 153));
        leavesAvailableText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leavesAvailableText.setText("0");
        getContentPane().add(leavesAvailableText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 80, -1));

        employeeDataButton.setForeground(new java.awt.Color(0, 102, 102));
        employeeDataButton.setText("Employee Records");
        employeeDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeDataButtonActionPerformed(evt);
            }
        });
        getContentPane().add(employeeDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 180, -1));

        attendanceButton.setForeground(new java.awt.Color(0, 102, 102));
        attendanceButton.setText("Attendance");
        attendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(attendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 180, -1));

        payslipButton.setForeground(new java.awt.Color(0, 102, 102));
        payslipButton.setText("Payslip");
        payslipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payslipButtonActionPerformed(evt);
            }
        });
        getContentPane().add(payslipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 180, -1));

        leaveButton.setForeground(new java.awt.Color(0, 102, 102));
        leaveButton.setText("Leave");
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(leaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 180, -1));

        overtimeButton.setForeground(new java.awt.Color(0, 102, 102));
        overtimeButton.setText("Overtime");
        overtimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overtimeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(overtimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 180, -1));

        logoutButton.setForeground(new java.awt.Color(0, 102, 102));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        payrollButton.setForeground(new java.awt.Color(0, 102, 102));
        payrollButton.setText("Payroll");
        payrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollButtonActionPerformed(evt);
            }
        });
        getContentPane().add(payrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 180, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/Home.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void employeeDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeDataButtonActionPerformed
        // Open PageEmployeeData
        new PageHREmployeeRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employeeDataButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void attendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceButtonActionPerformed
        new PageHRAttendanceRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_attendanceButtonActionPerformed

    private void payslipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payslipButtonActionPerformed
        new PageHRPayslip().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_payslipButtonActionPerformed

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed
        new PageHRLeave().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leaveButtonActionPerformed

    private void overtimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overtimeButtonActionPerformed
        new PageHROvertime().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_overtimeButtonActionPerformed

    private void payrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollButtonActionPerformed
        new PageHRPayroll().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_payrollButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageHRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageHRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageHRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageHRHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageHRHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private util.BlueButton attendanceButton;
    private util.BlueButton clockInButton;
    private javax.swing.JLabel clockInText;
    private util.BlueButton clockOutButton;
    private javax.swing.JLabel clockOutText;
    private javax.swing.JLabel dateTimeText;
    private util.BlueButton employeeDataButton;
    private javax.swing.JLabel fullNameText;
    private javax.swing.JLabel inLabel;
    private util.BlueButton leaveButton;
    private javax.swing.JLabel leavesAvailableText;
    private util.LightButton logoutButton;
    private javax.swing.JLabel outLabel;
    private util.BlueButton overtimeButton;
    private util.BlueButton payrollButton;
    private util.BlueButton payslipButton;
    private javax.swing.JLabel positionText;
    private javax.swing.JLabel totalWorkedHoursText;
    // End of variables declaration//GEN-END:variables
}
