package ui;

import util.SessionManager;

public class PageManagerAttendance extends ui.base.AbstractAttendancePage {

    public PageManagerAttendance() {
        initComponents();
        setupAttendancePage(attendanceTable, JDateChooser, totalWorkedHoursField, printAttendanceButton, SessionManager.getEmployeeID());
        backButton.addActionListener(e -> {
            new PageManagerHome().setVisible(true);
            this.dispose();
        });
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label10 = new javax.swing.JLabel();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        label9 = new javax.swing.JLabel();
        totalWorkedHoursField = new javax.swing.JTextField();
        backButton = new util.LightButton();
        viewAttendanceRecordsButton = new util.LightButton();
        printAttendanceButton = new util.LightButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label10.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(51, 51, 51));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label10.setText("Filter by Date:");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 110, 30));

        JDateChooser.setForeground(new java.awt.Color(0, 102, 102));
        JDateChooser.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        getContentPane().add(JDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 130, 30));

        label9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 51, 51));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("Total Hours:");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 100, 30));

        totalWorkedHoursField.setEditable(false);
        totalWorkedHoursField.setBackground(new java.awt.Color(204, 204, 204));
        totalWorkedHoursField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        totalWorkedHoursField.setForeground(new java.awt.Color(0, 102, 102));
        totalWorkedHoursField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        totalWorkedHoursField.setText("00 hrs, 00 min");
        getContentPane().add(totalWorkedHoursField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 130, 30));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        viewAttendanceRecordsButton.setForeground(new java.awt.Color(0, 102, 102));
        viewAttendanceRecordsButton.setText("View Attendance Records");
        viewAttendanceRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttendanceRecordsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewAttendanceRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 220, -1));

        printAttendanceButton.setForeground(new java.awt.Color(0, 102, 102));
        printAttendanceButton.setText("Print Attendance");
        printAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printAttendanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 160, -1));

        attendanceTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(attendanceTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 940, 400));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/AttendanceSummary.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewAttendanceRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttendanceRecordsButtonActionPerformed
        new PageManagerAttendanceRecords().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewAttendanceRecordsButtonActionPerformed

    private void printAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printAttendanceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printAttendanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageManagerAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageManagerAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageManagerAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageManagerAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageManagerAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateChooser;
    private javax.swing.JTable attendanceTable;
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label9;
    private util.LightButton printAttendanceButton;
    private javax.swing.JTextField totalWorkedHoursField;
    private util.LightButton viewAttendanceRecordsButton;
    // End of variables declaration//GEN-END:variables
}
