package ui;

public class PageManagerAttendanceRecords extends ui.base.AbstractAdminAttendancePage {

    public PageManagerAttendanceRecords() {
        initComponents();
        setupAdminAttendancePage(
            attendanceTable, JDateChooser, employeeIDComboBox, printAttendanceButton
        );
        backButton.addActionListener(e -> {
            new PageManagerHome().setVisible(true);
            this.dispose();
        });
        viewOwnRecordButton.addActionListener(e -> {
            new PageManagerAttendance().setVisible(true);
            this.dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeIDComboBox = new javax.swing.JComboBox<>();
        label10 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        backButton = new util.LightButton();
        viewOwnRecordButton = new util.LightButton();
        printAttendanceButton = new util.LightButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeIDComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        employeeIDComboBox.setForeground(new java.awt.Color(0, 102, 102));
        getContentPane().add(employeeIDComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 130, 30));

        label10.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(51, 51, 51));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label10.setText("   Find by ID:");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 100, 30));

        label9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 51, 51));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("Filter by Date:");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 110, 30));
        getContentPane().add(JDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 130, 30));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        viewOwnRecordButton.setForeground(new java.awt.Color(0, 102, 102));
        viewOwnRecordButton.setText("View Own Record");
        viewOwnRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOwnRecordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewOwnRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 220, -1));

        printAttendanceButton.setForeground(new java.awt.Color(0, 102, 102));
        printAttendanceButton.setText("Print Attendance");
        printAttendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printAttendanceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printAttendanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 160, -1));

        attendanceTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(attendanceTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 940, 400));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/AttendanceRecords.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewOwnRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOwnRecordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewOwnRecordButtonActionPerformed

    private void printAttendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printAttendanceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printAttendanceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageManagerAttendanceRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageManagerAttendanceRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageManagerAttendanceRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageManagerAttendanceRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageManagerAttendanceRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateChooser;
    private javax.swing.JTable attendanceTable;
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> employeeIDComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label9;
    private util.LightButton printAttendanceButton;
    private util.LightButton viewOwnRecordButton;
    // End of variables declaration//GEN-END:variables
}
