package ui;

import javax.swing.JLabel;
import javax.swing.JTextField;

public class PageEmployeeDataUpdateProfile extends ui.base.AbstractUpdateProfilePage {


    public PageEmployeeDataUpdateProfile() {
        initComponents();

        // 1) wire our three buttons + navigation callback
        setButtons(
            updateButton,
            cancelButton,
            backButton,
            () -> {
                new PageEmployeeData().setVisible(true);
                dispose();
            }
        );

        // 2) populate all fields from session
        initializeProfileUpdatePage();

        // 3) attach field-by-field validation
        attachValidationListeners();

        // 4) attach our formatters exactly once each
        attachPhoneFormatter(getPhoneNumberField());
        attachZipFormatter(getZipCodeField());

        // 5) track edits to unlock the Update button
        attachDirtyListeners(
            getPhoneNumberField(),
            getHouseNoField(),
            getStreetField(),
            getBarangayField(),
            getCityField(),
            getProvinceField(),
            getZipCodeField()
        );
    }

    @Override public JLabel getEmployeeIDText()   { return employeeIDText;   }
    @Override public JLabel getPositionText()     { return positionText;     }
    @Override public JLabel getSupervisorText()   { return supervisorText;   }
    @Override public JLabel getLastNameText()     { return lastNameText;     }
    @Override public JLabel getFirstNameText()    { return firstNameText;    }
    @Override public JLabel getBirthdayText()     { return birthdayText;     }

    @Override public JTextField getPhoneNumberField() { return phoneNumberField;    }
    @Override public JTextField getHouseNoField()     { return addressHouseNoField; }
    @Override public JTextField getStreetField()      { return addressStreetField;  }
    @Override public JTextField getBarangayField()    { return addressBarangayField;}
    @Override public JTextField getCityField()        { return addressCityField;    }
    @Override public JTextField getProvinceField()    { return addressProvinceField;}
    @Override public JTextField getZipCodeField()     { return addressZipCodeField; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new util.LightButton();
        updateButton = new util.BlueButton();
        backButton = new util.LightButton();
        addressHouseNoField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        label17 = new javax.swing.JLabel();
        addressProvinceField = new javax.swing.JTextField();
        label18 = new javax.swing.JLabel();
        addressZipCodeField = new javax.swing.JTextField();
        label15 = new javax.swing.JLabel();
        addressBarangayField = new javax.swing.JTextField();
        addressCityField = new javax.swing.JTextField();
        label16 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        addressStreetField = new javax.swing.JTextField();
        label13 = new javax.swing.JLabel();
        employeeIDText = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        positionText = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        supervisorText = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JLabel();
        firstNameText = new javax.swing.JLabel();
        birthdayText = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelButton.setForeground(new java.awt.Color(0, 102, 102));
        cancelButton.setText("Cancel");
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 120, -1));

        updateButton.setForeground(new java.awt.Color(0, 102, 102));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 120, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        addressHouseNoField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addressHouseNoField.setForeground(new java.awt.Color(0, 102, 102));
        addressHouseNoField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(addressHouseNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 100, -1));

        phoneNumberField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        phoneNumberField.setForeground(new java.awt.Color(0, 102, 102));
        phoneNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 170, -1));

        label17.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label17.setForeground(new java.awt.Color(51, 51, 51));
        label17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label17.setText("Province");
        getContentPane().add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 210, -1));

        addressProvinceField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addressProvinceField.setForeground(new java.awt.Color(0, 102, 102));
        addressProvinceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(addressProvinceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 180, -1));

        label18.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label18.setForeground(new java.awt.Color(51, 51, 51));
        label18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label18.setText("Zip Code");
        getContentPane().add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 140, -1));

        addressZipCodeField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addressZipCodeField.setForeground(new java.awt.Color(0, 102, 102));
        addressZipCodeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(addressZipCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 260, -1));

        label15.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label15.setForeground(new java.awt.Color(51, 51, 51));
        label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label15.setText("Barangay");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 210, -1));

        addressBarangayField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addressBarangayField.setForeground(new java.awt.Color(0, 102, 102));
        addressBarangayField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(addressBarangayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 180, -1));

        addressCityField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addressCityField.setForeground(new java.awt.Color(0, 102, 102));
        addressCityField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(addressCityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 260, -1));

        label16.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label16.setForeground(new java.awt.Color(51, 51, 51));
        label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label16.setText("City / Municipality");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 140, -1));

        label14.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label14.setForeground(new java.awt.Color(51, 51, 51));
        label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label14.setText("Street");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 220, -1));

        addressStreetField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addressStreetField.setForeground(new java.awt.Color(0, 102, 102));
        addressStreetField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(addressStreetField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 340, -1));

        label13.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label13.setForeground(new java.awt.Color(51, 51, 51));
        label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label13.setText("House No.");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 210, -1));

        employeeIDText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        employeeIDText.setForeground(new java.awt.Color(0, 51, 51));
        employeeIDText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeIDText.setText("Employee ID");
        getContentPane().add(employeeIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 210, -1));

        label10.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label10.setForeground(new java.awt.Color(0, 102, 102));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("Employee ID");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 210, -1));

        positionText.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        positionText.setForeground(new java.awt.Color(0, 51, 51));
        positionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionText.setText("Position");
        getContentPane().add(positionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 210, -1));

        label11.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label11.setForeground(new java.awt.Color(0, 102, 102));
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setText("Position");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 210, -1));

        supervisorText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        supervisorText.setForeground(new java.awt.Color(0, 51, 51));
        supervisorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supervisorText.setText("Supervisor");
        getContentPane().add(supervisorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 210, -1));

        label12.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label12.setForeground(new java.awt.Color(0, 102, 102));
        label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label12.setText("Supervisor");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 210, -1));

        label.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(51, 51, 51));
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText("Surname");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 210, -1));

        label9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 51, 51));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("First Name");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 210, -1));

        label1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("Birthdate");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 210, -1));

        lastNameText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lastNameText.setForeground(new java.awt.Color(0, 102, 102));
        lastNameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lastNameText.setText("Last Name");
        getContentPane().add(lastNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 360, -1));

        firstNameText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        firstNameText.setForeground(new java.awt.Color(0, 102, 102));
        firstNameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firstNameText.setText("First Name");
        getContentPane().add(firstNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 360, -1));

        birthdayText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        birthdayText.setForeground(new java.awt.Color(0, 102, 102));
        birthdayText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        birthdayText.setText("Birthdate");
        getContentPane().add(birthdayText, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 360, -1));

        label2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 51));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("Phone Number");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 210, -1));

        label3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 51, 51));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("Address");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 470, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ProfileUpdate.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageEmployeeDataUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageEmployeeDataUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageEmployeeDataUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageEmployeeDataUpdateProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageEmployeeDataUpdateProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressBarangayField;
    private javax.swing.JTextField addressCityField;
    private javax.swing.JTextField addressHouseNoField;
    private javax.swing.JTextField addressProvinceField;
    private javax.swing.JTextField addressStreetField;
    private javax.swing.JTextField addressZipCodeField;
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel birthdayText;
    private util.LightButton cancelButton;
    private javax.swing.JLabel employeeIDText;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JLabel positionText;
    private javax.swing.JLabel supervisorText;
    private util.BlueButton updateButton;
    // End of variables declaration//GEN-END:variables
}
