package ui;

import javax.swing.JOptionPane;

public class PageHREmployeeRegister extends ui.base.AbstractEmployeeRegisterPage {

    public PageHREmployeeRegister() {
        initComponents();
        setupRegisterPage(
          lastNameField, firstNameField, dateOfBirthCalendar,
          provinceField, cityMunicipalityField, barangayField,
          streetField, houseNumberField, zipCodeField,
          phoneNumberField, sssNumberField, philhealthNumberField,
          tinNumberField, pagibigNumberField,
          employeeRoleComboBox, employmentStatusComboBox,
          positionComboBox, departmentComboBox, supervisorComboBox,
          basicSalaryComboBox,
          backButton, cancelButton, confirmButton
        );

        backButton.addActionListener(evt -> {
            if (isDirty() && JOptionPane.showConfirmDialog(
                    this, "You have unsaved changes. Discard?", "Confirm", JOptionPane.YES_NO_OPTION
            ) != JOptionPane.YES_OPTION) return;
            new PageHREmployeeRecords().setVisible(true);
            dispose();
        });
        cancelButton.addActionListener(backButton.getActionListeners()[0]);
    }

    @Override
    protected void onRegisterSuccess() { new PageHREmployeeRecords().setVisible(true); dispose(); }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new util.LightButton();
        confirmButton = new util.BlueButton();
        backButton = new util.LightButton();
        label1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        employmentStatusComboBox = new javax.swing.JComboBox<>();
        label15 = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        label16 = new javax.swing.JLabel();
        label17 = new javax.swing.JLabel();
        label19 = new javax.swing.JLabel();
        sssNumberField = new javax.swing.JTextField();
        label20 = new javax.swing.JLabel();
        philhealthNumberField = new javax.swing.JTextField();
        label21 = new javax.swing.JLabel();
        tinNumberField = new javax.swing.JTextField();
        label22 = new javax.swing.JLabel();
        pagibigNumberField = new javax.swing.JTextField();
        label18 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        barangayField = new javax.swing.JTextField();
        label14 = new javax.swing.JLabel();
        streetField = new javax.swing.JTextField();
        label11 = new javax.swing.JLabel();
        provinceField = new javax.swing.JTextField();
        label12 = new javax.swing.JLabel();
        cityMunicipalityField = new javax.swing.JTextField();
        label23 = new javax.swing.JLabel();
        houseNumberField = new javax.swing.JTextField();
        label24 = new javax.swing.JLabel();
        zipCodeField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        supervisorComboBox = new javax.swing.JComboBox<>();
        departmentComboBox = new javax.swing.JComboBox<>();
        positionComboBox = new javax.swing.JComboBox<>();
        label25 = new javax.swing.JLabel();
        basicSalaryComboBox = new javax.swing.JComboBox<>();
        label3 = new javax.swing.JLabel();
        employeeRoleComboBox = new javax.swing.JComboBox<>();
        dateOfBirthCalendar = new com.toedter.calendar.JDateChooser();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelButton.setForeground(new java.awt.Color(0, 102, 102));
        cancelButton.setText("Cancel");
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 120, -1));

        confirmButton.setForeground(new java.awt.Color(0, 102, 102));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 120, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        label1.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("Last Name");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 90, -1));

        label.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(51, 51, 51));
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText("Employment Status");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 140, -1));

        label9.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 51, 51));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("First Name");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 90, -1));

        label2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 51));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("Date of Birth");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 90, -1));

        employmentStatusComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        employmentStatusComboBox.setForeground(new java.awt.Color(0, 102, 102));
        employmentStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Probationary", "Regular" }));
        getContentPane().add(employmentStatusComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 190, -1));

        label15.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label15.setForeground(new java.awt.Color(51, 51, 51));
        label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label15.setText("Phone Number");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 190, -1));

        phoneNumberField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        phoneNumberField.setForeground(new java.awt.Color(0, 102, 102));
        phoneNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(phoneNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 190, -1));

        label16.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label16.setForeground(new java.awt.Color(51, 51, 51));
        label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label16.setText("Position");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 90, -1));

        label17.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label17.setForeground(new java.awt.Color(51, 51, 51));
        label17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label17.setText("Supervisor");
        getContentPane().add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 90, -1));

        label19.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label19.setForeground(new java.awt.Color(51, 51, 51));
        label19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label19.setText("SSS No.");
        getContentPane().add(label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 90, -1));

        sssNumberField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        sssNumberField.setForeground(new java.awt.Color(0, 102, 102));
        sssNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(sssNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 190, -1));

        label20.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label20.setForeground(new java.awt.Color(51, 51, 51));
        label20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label20.setText("Philhealth No.");
        getContentPane().add(label20, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 110, -1));

        philhealthNumberField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        philhealthNumberField.setForeground(new java.awt.Color(0, 102, 102));
        philhealthNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(philhealthNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 190, -1));

        label21.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label21.setForeground(new java.awt.Color(51, 51, 51));
        label21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label21.setText("TIN No.");
        getContentPane().add(label21, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 90, -1));

        tinNumberField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        tinNumberField.setForeground(new java.awt.Color(0, 102, 102));
        tinNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(tinNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 190, -1));

        label22.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label22.setForeground(new java.awt.Color(51, 51, 51));
        label22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label22.setText("Pag-Ibig No.");
        getContentPane().add(label22, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 90, -1));

        pagibigNumberField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        pagibigNumberField.setForeground(new java.awt.Color(0, 102, 102));
        pagibigNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(pagibigNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 190, -1));

        label18.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label18.setForeground(new java.awt.Color(51, 51, 51));
        label18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label18.setText("Department");
        getContentPane().add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 90, -1));

        label13.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label13.setForeground(new java.awt.Color(51, 51, 51));
        label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label13.setText("Barangay");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 190, -1));

        barangayField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        barangayField.setForeground(new java.awt.Color(0, 102, 102));
        barangayField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(barangayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 190, -1));

        label14.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label14.setForeground(new java.awt.Color(51, 51, 51));
        label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label14.setText("Street");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 90, -1));

        streetField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        streetField.setForeground(new java.awt.Color(0, 102, 102));
        streetField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(streetField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 190, -1));

        label11.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label11.setForeground(new java.awt.Color(51, 51, 51));
        label11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label11.setText("Province");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 190, -1));

        provinceField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        provinceField.setForeground(new java.awt.Color(0, 102, 102));
        provinceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(provinceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 190, -1));

        label12.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label12.setForeground(new java.awt.Color(51, 51, 51));
        label12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label12.setText("City / Municipality");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 190, -1));

        cityMunicipalityField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        cityMunicipalityField.setForeground(new java.awt.Color(0, 102, 102));
        cityMunicipalityField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(cityMunicipalityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 190, -1));

        label23.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label23.setForeground(new java.awt.Color(51, 51, 51));
        label23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label23.setText("House No.");
        getContentPane().add(label23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 90, -1));

        houseNumberField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        houseNumberField.setForeground(new java.awt.Color(0, 102, 102));
        houseNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(houseNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 190, -1));

        label24.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label24.setForeground(new java.awt.Color(51, 51, 51));
        label24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label24.setText("Zip Code");
        getContentPane().add(label24, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 90, -1));

        zipCodeField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        zipCodeField.setForeground(new java.awt.Color(0, 102, 102));
        zipCodeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(zipCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 190, -1));

        firstNameField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        firstNameField.setForeground(new java.awt.Color(0, 102, 102));
        firstNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 190, -1));

        lastNameField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        lastNameField.setForeground(new java.awt.Color(0, 102, 102));
        lastNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 190, -1));

        supervisorComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        supervisorComboBox.setForeground(new java.awt.Color(0, 102, 102));
        supervisorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garcia, Manuel III", "Lim, Antonio", "Aquino, Bianca Sofia", "Reyes, Isabella", "Villanueva, Andrea Mae", "San Jose, Brad", "Romualdez, Alice", "Alvaro, Roderick", "Salcedo, Anthony", "Mata, Christian", "De Leon, Selena" }));
        getContentPane().add(supervisorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 190, -1));

        departmentComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        departmentComboBox.setForeground(new java.awt.Color(0, 102, 102));
        departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer Service", "Supply Chain & Logistics", "Sales & Marketing", "Payroll", "Accounting", "HR", "IT", "Executive" }));
        getContentPane().add(departmentComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 190, -1));

        positionComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        positionComboBox.setForeground(new java.awt.Color(0, 102, 102));
        positionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer Service and Relations", "Supply Chain and Logistics", "Sales & Marketing", "Account Rank and File", "Account Team Leader", "Account Manager", "Payroll Rank and File", "Payroll Team Leader", "Payroll Manager", "Accounting Head", "HR Rank and File", "HR Team Leader", "HR Manager", "IT Operations and Systems", "Chief Marketing Officer", "Chief Finance Officer", "Chief Operating Officer", "Chief Executive Officer" }));
        getContentPane().add(positionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 190, -1));

        label25.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label25.setForeground(new java.awt.Color(51, 51, 51));
        label25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label25.setText("Basic Salary");
        getContentPane().add(label25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 90, -1));

        basicSalaryComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        basicSalaryComboBox.setForeground(new java.awt.Color(0, 102, 102));
        basicSalaryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "₱22,500", "₱23,250", "₱24,000", "₱24,750", "₱38,475", "₱41,850", "₱42,975 ", "₱50,825", "₱52,670", "₱53,500", "₱60,000", "₱90,000" }));
        getContentPane().add(basicSalaryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 190, -1));

        label3.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 51, 51));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("Employee Role");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 140, -1));

        employeeRoleComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        employeeRoleComboBox.setForeground(new java.awt.Color(0, 102, 102));
        employeeRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "HR", "IT", "Finance", "Manager" }));
        getContentPane().add(employeeRoleComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 190, -1));

        dateOfBirthCalendar.setForeground(new java.awt.Color(0, 102, 102));
        dateOfBirthCalendar.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        getContentPane().add(dateOfBirthCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 190, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/HRCreateEmployee.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageHREmployeeRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageHREmployeeRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageHREmployeeRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageHREmployeeRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageHREmployeeRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public util.LightButton backButton;
    private javax.swing.JLabel background;
    public javax.swing.JTextField barangayField;
    public javax.swing.JComboBox<String> basicSalaryComboBox;
    public util.LightButton cancelButton;
    public javax.swing.JTextField cityMunicipalityField;
    public util.BlueButton confirmButton;
    public com.toedter.calendar.JDateChooser dateOfBirthCalendar;
    public javax.swing.JComboBox<String> departmentComboBox;
    public javax.swing.JComboBox<String> employeeRoleComboBox;
    public javax.swing.JComboBox<String> employmentStatusComboBox;
    public javax.swing.JTextField firstNameField;
    public javax.swing.JTextField houseNumberField;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label20;
    private javax.swing.JLabel label21;
    private javax.swing.JLabel label22;
    private javax.swing.JLabel label23;
    private javax.swing.JLabel label24;
    private javax.swing.JLabel label25;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label9;
    public javax.swing.JTextField lastNameField;
    public javax.swing.JTextField pagibigNumberField;
    public javax.swing.JTextField philhealthNumberField;
    public javax.swing.JTextField phoneNumberField;
    public javax.swing.JComboBox<String> positionComboBox;
    public javax.swing.JTextField provinceField;
    public javax.swing.JTextField sssNumberField;
    public javax.swing.JTextField streetField;
    public javax.swing.JComboBox<String> supervisorComboBox;
    public javax.swing.JTextField tinNumberField;
    public javax.swing.JTextField zipCodeField;
    // End of variables declaration//GEN-END:variables
}
