package ui;

import javax.swing.JOptionPane;

public class PageHROvertimeRequest extends ui.base.AbstractOvertimeRequestPage {

    public PageHROvertimeRequest() {
        initComponents();

        // Link all components and logic from abstract base class
        setComponentReferences(startDateCalendar, overtimeHoursJSpinner, overtimeReasonTextArea, submitButton);

        // Spinner default: set value to 1 hour initially (not 0)
        overtimeHoursJSpinner.setValue(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overtimeReasonTextArea = new javax.swing.JTextArea();
        overtimeHoursJSpinner = new javax.swing.JSpinner();
        label1 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        startDateCalendar = new com.toedter.calendar.JDateChooser();
        cancelButton = new util.LightButton();
        submitButton = new util.BlueButton();
        backButton = new util.LightButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label5.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(51, 51, 51));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("Reason for Overtime");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 490, 30));

        overtimeReasonTextArea.setColumns(20);
        overtimeReasonTextArea.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        overtimeReasonTextArea.setRows(5);
        jScrollPane1.setViewportView(overtimeReasonTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 490, 220));

        overtimeHoursJSpinner.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        overtimeHoursJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));
        getContentPane().add(overtimeHoursJSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 110, 30));

        label1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("Overtime Date");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 110, 30));

        label4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(51, 51, 51));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("Overtime Hours");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 110, 30));

        startDateCalendar.setForeground(new java.awt.Color(0, 102, 102));
        startDateCalendar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        getContentPane().add(startDateCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 230, 30));

        cancelButton.setForeground(new java.awt.Color(0, 102, 102));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 120, -1));

        submitButton.setForeground(new java.awt.Color(0, 102, 102));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 120, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/OvertimeRequest.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if (!isFormDirty() || 
            JOptionPane.showConfirmDialog(this, "Discard changes to your overtime request?", "Cancel Request", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // Go back to overtime page
            new PageHROvertime().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (trySubmitRequest()) {
            new PageHROvertime().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if (!isFormDirty() || 
            JOptionPane.showConfirmDialog(this, "Discard changes to your overtime request?", "Cancel Request", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // Go back to overtime page
            new PageHROvertime().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageHROvertimeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageHROvertimeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageHROvertimeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageHROvertimeRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageHROvertimeRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private util.LightButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JSpinner overtimeHoursJSpinner;
    private javax.swing.JTextArea overtimeReasonTextArea;
    private com.toedter.calendar.JDateChooser startDateCalendar;
    private util.BlueButton submitButton;
    // End of variables declaration//GEN-END:variables
}
