package ui;

import pojo.Overtime;

public class PageManagerOvertime extends ui.base.AbstractOvertimePage {

    public PageManagerOvertime() {
        initComponents();
        setComponentReferences(overtimeTable, JDateChooser);
    }

    @Override
    protected void onOvertimeUpdateSelected(Overtime selectedOvertime) {
        new PageManagerOvertimeRequestUpdate(selectedOvertime).setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewOvertimeRecordsButton = new util.LightButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        overtimeTable = new javax.swing.JTable();
        overtimeRequestButton = new util.LightButton();
        backButton = new util.LightButton();
        label8 = new javax.swing.JLabel();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewOvertimeRecordsButton.setForeground(new java.awt.Color(0, 102, 102));
        viewOvertimeRecordsButton.setText("View Overtime Records");
        viewOvertimeRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOvertimeRecordsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(viewOvertimeRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 220, -1));

        overtimeTable.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        overtimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(overtimeTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 940, 400));

        overtimeRequestButton.setForeground(new java.awt.Color(0, 102, 102));
        overtimeRequestButton.setText("Create Request");
        overtimeRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overtimeRequestButtonActionPerformed(evt);
            }
        });
        getContentPane().add(overtimeRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 160, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        label8.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(51, 51, 51));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label8.setText("Filter by Date:");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 110, 30));

        JDateChooser.setForeground(new java.awt.Color(0, 102, 102));
        JDateChooser.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        getContentPane().add(JDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 130, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/MyOvertimeHistory.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void overtimeRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overtimeRequestButtonActionPerformed
        new PageManagerOvertimeRequest().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_overtimeRequestButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new PageManagerHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void viewOvertimeRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOvertimeRecordsButtonActionPerformed
        new PageManagerOvertimeAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewOvertimeRecordsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageManagerOvertime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageManagerOvertime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageManagerOvertime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageManagerOvertime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageManagerOvertime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateChooser;
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label8;
    private util.LightButton overtimeRequestButton;
    private javax.swing.JTable overtimeTable;
    private util.LightButton viewOvertimeRecordsButton;
    // End of variables declaration//GEN-END:variables
}
