package ui;

import pojo.Leave;

public class PageFinanceLeaveRequestUpdate extends ui.base.AbstractLeaveRequestUpdatePage {

    public PageFinanceLeaveRequestUpdate() {
        initComponents();
        // Always set component references after initializing UI
        setComponentReferences(
            leaveTypeComboBox,
            startDateCalendar,
            endDateCalendar,
            leaveReasonTextArea,
            leaveAvailableField,
            submitButton
        );
        // Disable all fields until a leave is loaded
        setFieldsEnabled(false);
    }

    // Loads leave data into the form for editing
    public void loadLeaveForUpdate(Leave leave) {
        setLeaveData(leave);
        setFieldsEnabled(true);
    }

    // Disables or enables all inputs (except cancel/back)
    private void setFieldsEnabled(boolean enabled) {
        leaveTypeComboBox.setEnabled(enabled);
        startDateCalendar.setEnabled(enabled);
        endDateCalendar.setEnabled(enabled);
        leaveReasonTextArea.setEnabled(enabled);
        submitButton.setEnabled(enabled);
    }

    @Override
    protected void onUpdateRequestSubmitted() {
        // After successful update, go back to leave history and show message
        javax.swing.JOptionPane.showMessageDialog(this, "Leave request updated successfully.", "Notice", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        new PageFinanceLeave().setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaveReasonTextArea = new javax.swing.JTextArea();
        label3 = new javax.swing.JLabel();
        leaveAvailableField = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        endDateCalendar = new com.toedter.calendar.JDateChooser();
        label1 = new javax.swing.JLabel();
        startDateCalendar = new com.toedter.calendar.JDateChooser();
        label = new javax.swing.JLabel();
        leaveTypeComboBox = new javax.swing.JComboBox<>();
        cancelButton = new util.LightButton();
        submitButton = new util.BlueButton();
        backButton = new util.LightButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label4.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(51, 51, 51));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("Reason for Leave");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 490, 30));

        leaveReasonTextArea.setColumns(20);
        leaveReasonTextArea.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        leaveReasonTextArea.setRows(5);
        jScrollPane1.setViewportView(leaveReasonTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 490, 220));

        label3.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 51, 51));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label3.setText("Leave Available:");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 120, 30));

        leaveAvailableField.setEditable(false);
        leaveAvailableField.setBackground(new java.awt.Color(204, 204, 204));
        leaveAvailableField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        leaveAvailableField.setForeground(new java.awt.Color(0, 102, 102));
        leaveAvailableField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(leaveAvailableField, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 110, 30));

        label2.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(51, 51, 51));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label2.setText("End Date");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 230, 30));

        endDateCalendar.setForeground(new java.awt.Color(0, 102, 102));
        endDateCalendar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        getContentPane().add(endDateCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 230, 30));

        label1.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label1.setText("Start Date");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 210, 30));

        startDateCalendar.setForeground(new java.awt.Color(0, 102, 102));
        startDateCalendar.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        getContentPane().add(startDateCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 230, 30));

        label.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label.setForeground(new java.awt.Color(51, 51, 51));
        label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label.setText("Leave Type");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, 30));

        leaveTypeComboBox.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        leaveTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacation", "Sick", "Emergency", "Maternity", "Paternity", "Bereavement" }));
        getContentPane().add(leaveTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 160, 30));

        cancelButton.setForeground(new java.awt.Color(0, 102, 102));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 120, -1));

        submitButton.setForeground(new java.awt.Color(0, 102, 102));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 120, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/LeaveRequest.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        new PageFinanceLeave().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new PageFinanceLeave().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageFinanceLeaveRequestUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageFinanceLeaveRequestUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageFinanceLeaveRequestUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageFinanceLeaveRequestUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageFinanceLeaveRequestUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private util.LightButton cancelButton;
    private com.toedter.calendar.JDateChooser endDateCalendar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JTextField leaveAvailableField;
    private javax.swing.JTextArea leaveReasonTextArea;
    private javax.swing.JComboBox<String> leaveTypeComboBox;
    private com.toedter.calendar.JDateChooser startDateCalendar;
    private util.BlueButton submitButton;
    // End of variables declaration//GEN-END:variables
}
