package ui;

import java.awt.event.ActionListener;
import javax.swing.JLabel;

public class PageITEmployeeDataUpdateCredential extends ui.base.AbstractUpdateCredentialPage {

    public PageITEmployeeDataUpdateCredential() {
        initComponents();

        // ─── 1) Remove all auto‐generated listeners ───
        for (ActionListener al : updateButton.getActionListeners()) {
            updateButton.removeActionListener(al);
        }
        for (ActionListener al : cancelButton.getActionListeners()) {
            cancelButton.removeActionListener(al);
        }
        for (ActionListener al : backButton.getActionListeners()) {
            backButton.removeActionListener(al);
        }

        // ─── 2) Wire in the base‐class behavior ───
        setPasswordFieldsAndErrorLabel(
            passwordCurrentField,
            passwordNewField,
            passwordReEnterField,
            errorMessageLabel
        );

        initializeUpdateCredentialPage();

        setButtons(
            updateButton,
            cancelButton,
            backButton,
            () -> {
                new PageITEmployeeData().setVisible(true);
                dispose();
            }
        );

        attachDirtyListeners(
            passwordCurrentField,
            passwordNewField,
            passwordReEnterField
        );
    }

    @Override protected JLabel getUsernameText()   { return usernameText;   }
    @Override protected JLabel getEmailText()      { return emailText;      }
    @Override protected JLabel getEmployeeIDText() { return employeeIDText; }
    @Override protected JLabel getPositionText()   { return positionText;   }
    @Override protected JLabel getSupervisorText() { return supervisorText; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label15 = new javax.swing.JLabel();
        backButton = new util.LightButton();
        passwordReEnterField = new javax.swing.JPasswordField();
        passwordNewField = new javax.swing.JPasswordField();
        updateButton = new util.BlueButton();
        label9 = new javax.swing.JLabel();
        errorMessageLabel = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        label18 = new javax.swing.JLabel();
        employeeIDText = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        passwordCurrentField = new javax.swing.JPasswordField();
        usernameText = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label13 = new javax.swing.JLabel();
        label16 = new javax.swing.JLabel();
        positionText = new javax.swing.JLabel();
        emailText = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        supervisorText = new javax.swing.JLabel();
        cancelButton = new util.LightButton();
        label17 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label15.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label15.setForeground(new java.awt.Color(51, 51, 51));
        label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label15.setText("* Must contain at least 1 lowercase letter (a-z)  ");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 430, -1));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        passwordReEnterField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        passwordReEnterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordReEnterFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordReEnterField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 260, -1));

        passwordNewField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        passwordNewField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordNewFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordNewField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 260, -1));

        updateButton.setForeground(new java.awt.Color(0, 102, 102));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 120, -1));

        label9.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 51, 51));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("Password Requirements:");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 220, -1));

        errorMessageLabel.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        errorMessageLabel.setForeground(new java.awt.Color(255, 255, 255));
        errorMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        errorMessageLabel.setText("Re-Enter Password");
        getContentPane().add(errorMessageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 260, -1));

        label7.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(51, 51, 51));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label7.setText("Name");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 130, -1));

        label5.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(51, 51, 51));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("Email");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 130, -1));

        label14.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label14.setForeground(new java.awt.Color(51, 51, 51));
        label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label14.setText("* Must contain at least 1 uppercase letter (A-Z)  ");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 430, -1));

        label18.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label18.setForeground(new java.awt.Color(51, 51, 51));
        label18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label18.setText("New Password");
        getContentPane().add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 140, -1));

        employeeIDText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        employeeIDText.setForeground(new java.awt.Color(0, 51, 51));
        employeeIDText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeIDText.setText("Employee ID");
        getContentPane().add(employeeIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 210, -1));

        label10.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label10.setForeground(new java.awt.Color(0, 102, 102));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label10.setText("Employee ID");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 210, -1));

        label11.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label11.setForeground(new java.awt.Color(0, 102, 102));
        label11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label11.setText("Position");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 210, -1));

        passwordCurrentField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        passwordCurrentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCurrentFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordCurrentField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 260, -1));

        usernameText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        usernameText.setForeground(new java.awt.Color(0, 102, 102));
        usernameText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameText.setText("Username");
        getContentPane().add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 260, -1));

        label8.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(51, 51, 51));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label8.setText("Re-Enter Password");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 140, -1));

        label6.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(51, 51, 51));
        label6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label6.setText("Current Password");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 140, -1));

        label13.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label13.setForeground(new java.awt.Color(51, 51, 51));
        label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label13.setText("* Must be at least 8 characters long");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 420, -1));

        label16.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label16.setForeground(new java.awt.Color(51, 51, 51));
        label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label16.setText("* Must include at least 1 number (0-9)  ");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 430, -1));

        positionText.setFont(new java.awt.Font("Inter", 1, 16)); // NOI18N
        positionText.setForeground(new java.awt.Color(0, 51, 51));
        positionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        positionText.setText("Position");
        getContentPane().add(positionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 210, -1));

        emailText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        emailText.setForeground(new java.awt.Color(0, 102, 102));
        emailText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        emailText.setText("Email");
        getContentPane().add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 260, -1));

        label12.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label12.setForeground(new java.awt.Color(0, 102, 102));
        label12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label12.setText("Supervisor");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 210, -1));

        supervisorText.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        supervisorText.setForeground(new java.awt.Color(0, 51, 51));
        supervisorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supervisorText.setText("Supervisor");
        getContentPane().add(supervisorText, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 210, -1));

        cancelButton.setForeground(new java.awt.Color(0, 102, 102));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 120, -1));

        label17.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label17.setForeground(new java.awt.Color(51, 51, 51));
        label17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label17.setText("* Must include at least 1 special character (! @ # $ % ^ & * etc.)  ");
        getContentPane().add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 440, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ProfileUpdateCredentials.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void passwordReEnterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordReEnterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordReEnterFieldActionPerformed

    private void passwordNewFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordNewFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordNewFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        handleUpdate();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void passwordCurrentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCurrentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordCurrentFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageITEmployeeDataUpdateCredential.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageITEmployeeDataUpdateCredential.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageITEmployeeDataUpdateCredential.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageITEmployeeDataUpdateCredential.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageITEmployeeDataUpdateCredential().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private util.LightButton cancelButton;
    private javax.swing.JLabel emailText;
    private javax.swing.JLabel employeeIDText;
    private javax.swing.JLabel errorMessageLabel;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JPasswordField passwordCurrentField;
    private javax.swing.JPasswordField passwordNewField;
    private javax.swing.JPasswordField passwordReEnterField;
    private javax.swing.JLabel positionText;
    private javax.swing.JLabel supervisorText;
    private util.BlueButton updateButton;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
