package ui;

public class PageManagerPayslip extends ui.base.AbstractPayslipPage {

    public PageManagerPayslip() {
        super();
        initComponents();
        // Now link UI fields to the abstract logic
        setComponentReferences(
            payslipPeriodComboBox,
            JDateChooser,
            monthlyRateField, hourlyRateField, daysWorkedField, hoursWorkedField, overtimeField, overtimePayField,
            totalGrossIncomeField, riceSubsidyField, phoneAllowanceField, clothingAllowanceField, totalBenefitsField,
            sssField, philhealthField, pagibigField, withholdingTaxField, totalDeductionsField, grossIncomeField,
            benefitsField, deductionsField, takeHomePayField,
            printPayslipButton, backButton
        );
        // Back button event can be adjusted as needed:
        backButton.addActionListener(e -> {
            new PageManagerHome().setVisible(true);
            this.dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label16 = new javax.swing.JLabel();
        benefitsField = new javax.swing.JTextField();
        printPayslipButton = new util.LightButton();
        label = new javax.swing.JLabel();
        label17 = new javax.swing.JLabel();
        pagibigField = new javax.swing.JTextField();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        label13 = new javax.swing.JLabel();
        label19 = new javax.swing.JLabel();
        totalBenefitsField = new javax.swing.JTextField();
        totalDeductionsField = new javax.swing.JTextField();
        label8 = new javax.swing.JLabel();
        deductionsField = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        label18 = new javax.swing.JLabel();
        label15 = new javax.swing.JLabel();
        phoneAllowanceField = new javax.swing.JTextField();
        sssField = new javax.swing.JTextField();
        riceSubsidyField = new javax.swing.JTextField();
        label14 = new javax.swing.JLabel();
        label24 = new javax.swing.JLabel();
        clothingAllowanceField = new javax.swing.JTextField();
        grossIncomeField = new javax.swing.JTextField();
        withholdingTaxField = new javax.swing.JTextField();
        takeHomePayField = new javax.swing.JTextField();
        label21 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label20 = new javax.swing.JLabel();
        label22 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label23 = new javax.swing.JLabel();
        philhealthField = new javax.swing.JTextField();
        label9 = new javax.swing.JLabel();
        daysWorkedField = new javax.swing.JTextField();
        backButton = new util.LightButton();
        label25 = new javax.swing.JLabel();
        payslipPeriodComboBox = new javax.swing.JComboBox<>();
        label4 = new javax.swing.JLabel();
        monthlyRateField = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        hourlyRateField = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        hoursWorkedField = new javax.swing.JTextField();
        label6 = new javax.swing.JLabel();
        overtimeField = new javax.swing.JTextField();
        label10 = new javax.swing.JLabel();
        overtimePayField = new javax.swing.JTextField();
        label11 = new javax.swing.JLabel();
        totalGrossIncomeField = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MotorPH Payroll System");
        setMaximumSize(new java.awt.Dimension(1040, 590));
        setMinimumSize(new java.awt.Dimension(1040, 590));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label16.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label16.setForeground(new java.awt.Color(0, 102, 102));
        label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label16.setText("Total Benefits");
        getContentPane().add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 110, -1));

        benefitsField.setEditable(false);
        benefitsField.setBackground(new java.awt.Color(255, 255, 255));
        benefitsField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        benefitsField.setForeground(new java.awt.Color(51, 51, 51));
        benefitsField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        benefitsField.setText("0");
        benefitsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benefitsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(benefitsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 230, 30));

        printPayslipButton.setForeground(new java.awt.Color(0, 102, 102));
        printPayslipButton.setText("Print Payslip");
        printPayslipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printPayslipButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printPayslipButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 160, -1));

        label.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        label.setForeground(new java.awt.Color(0, 102, 102));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Earnings");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 280, -1));

        label17.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label17.setForeground(new java.awt.Color(51, 51, 51));
        label17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label17.setText("Pagibig");
        getContentPane().add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 110, -1));

        pagibigField.setEditable(false);
        pagibigField.setBackground(new java.awt.Color(255, 255, 255));
        pagibigField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        pagibigField.setForeground(new java.awt.Color(51, 51, 51));
        pagibigField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pagibigField.setText("0");
        pagibigField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagibigFieldActionPerformed(evt);
            }
        });
        getContentPane().add(pagibigField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 110, 30));

        JDateChooser.setForeground(new java.awt.Color(0, 102, 102));
        JDateChooser.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        getContentPane().add(JDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 130, 30));

        label13.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label13.setForeground(new java.awt.Color(51, 51, 51));
        label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label13.setText("Clothing Allowance");
        getContentPane().add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 110, -1));

        label19.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label19.setForeground(new java.awt.Color(0, 102, 102));
        label19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label19.setText("Total Deductions");
        getContentPane().add(label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 230, -1));

        totalBenefitsField.setEditable(false);
        totalBenefitsField.setBackground(new java.awt.Color(255, 255, 255));
        totalBenefitsField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        totalBenefitsField.setForeground(new java.awt.Color(51, 51, 51));
        totalBenefitsField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        totalBenefitsField.setText("0");
        totalBenefitsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBenefitsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalBenefitsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 110, 30));

        totalDeductionsField.setEditable(false);
        totalDeductionsField.setBackground(new java.awt.Color(255, 255, 255));
        totalDeductionsField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        totalDeductionsField.setForeground(new java.awt.Color(51, 51, 51));
        totalDeductionsField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        totalDeductionsField.setText("0");
        totalDeductionsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDeductionsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalDeductionsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 230, 30));

        label8.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label8.setForeground(new java.awt.Color(51, 51, 51));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label8.setText("Filter by Date:");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 110, 30));

        deductionsField.setEditable(false);
        deductionsField.setBackground(new java.awt.Color(255, 255, 255));
        deductionsField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        deductionsField.setForeground(new java.awt.Color(51, 51, 51));
        deductionsField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        deductionsField.setText("0");
        getContentPane().add(deductionsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 230, 30));

        label1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 102, 102));
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Benefits");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 280, -1));

        label18.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label18.setForeground(new java.awt.Color(51, 51, 51));
        label18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label18.setText("Philhealth");
        getContentPane().add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 110, -1));

        label15.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label15.setForeground(new java.awt.Color(51, 51, 51));
        label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label15.setText("Phone Allowance");
        getContentPane().add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 110, -1));

        phoneAllowanceField.setEditable(false);
        phoneAllowanceField.setBackground(new java.awt.Color(255, 255, 255));
        phoneAllowanceField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        phoneAllowanceField.setForeground(new java.awt.Color(51, 51, 51));
        phoneAllowanceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneAllowanceField.setText("0");
        getContentPane().add(phoneAllowanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 110, 30));

        sssField.setEditable(false);
        sssField.setBackground(new java.awt.Color(255, 255, 255));
        sssField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        sssField.setForeground(new java.awt.Color(51, 51, 51));
        sssField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        sssField.setText("0");
        getContentPane().add(sssField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 110, 30));

        riceSubsidyField.setEditable(false);
        riceSubsidyField.setBackground(new java.awt.Color(255, 255, 255));
        riceSubsidyField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        riceSubsidyField.setForeground(new java.awt.Color(51, 51, 51));
        riceSubsidyField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        riceSubsidyField.setText("0");
        getContentPane().add(riceSubsidyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 110, 30));

        label14.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label14.setForeground(new java.awt.Color(51, 51, 51));
        label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label14.setText("SSS");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 110, -1));

        label24.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label24.setForeground(new java.awt.Color(0, 102, 102));
        label24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label24.setText("Net Pay (After Deductions)");
        getContentPane().add(label24, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 190, -1));

        clothingAllowanceField.setEditable(false);
        clothingAllowanceField.setBackground(new java.awt.Color(255, 255, 255));
        clothingAllowanceField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        clothingAllowanceField.setForeground(new java.awt.Color(51, 51, 51));
        clothingAllowanceField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clothingAllowanceField.setText("0");
        clothingAllowanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clothingAllowanceFieldActionPerformed(evt);
            }
        });
        getContentPane().add(clothingAllowanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 110, 30));

        grossIncomeField.setEditable(false);
        grossIncomeField.setBackground(new java.awt.Color(255, 255, 255));
        grossIncomeField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        grossIncomeField.setForeground(new java.awt.Color(51, 51, 51));
        grossIncomeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        grossIncomeField.setText("0");
        getContentPane().add(grossIncomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 230, 30));

        withholdingTaxField.setEditable(false);
        withholdingTaxField.setBackground(new java.awt.Color(255, 255, 255));
        withholdingTaxField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        withholdingTaxField.setForeground(new java.awt.Color(51, 51, 51));
        withholdingTaxField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        withholdingTaxField.setText("0");
        getContentPane().add(withholdingTaxField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 110, 30));

        takeHomePayField.setEditable(false);
        takeHomePayField.setBackground(new java.awt.Color(255, 255, 255));
        takeHomePayField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        takeHomePayField.setForeground(new java.awt.Color(51, 51, 51));
        takeHomePayField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        takeHomePayField.setText("0");
        getContentPane().add(takeHomePayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 230, 30));

        label21.setFont(new java.awt.Font("Inter", 2, 12)); // NOI18N
        label21.setForeground(new java.awt.Color(51, 51, 51));
        label21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label21.setText("Gross Income");
        getContentPane().add(label21, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 130, -1));

        label3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 102, 102));
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Summary");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 280, -1));

        label20.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label20.setForeground(new java.awt.Color(51, 51, 51));
        label20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label20.setText("Withholding Tax");
        getContentPane().add(label20, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 110, -1));

        label22.setFont(new java.awt.Font("Inter", 2, 12)); // NOI18N
        label22.setForeground(new java.awt.Color(51, 51, 51));
        label22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label22.setText("Total Benefits");
        getContentPane().add(label22, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 110, -1));

        label2.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 102, 102));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Deductions");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 280, -1));

        label12.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label12.setForeground(new java.awt.Color(51, 51, 51));
        label12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label12.setText("Rice Subsidy");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 110, -1));

        label23.setFont(new java.awt.Font("Inter", 2, 12)); // NOI18N
        label23.setForeground(new java.awt.Color(51, 51, 51));
        label23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label23.setText("Total Deductions");
        getContentPane().add(label23, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 110, -1));

        philhealthField.setEditable(false);
        philhealthField.setBackground(new java.awt.Color(255, 255, 255));
        philhealthField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        philhealthField.setForeground(new java.awt.Color(51, 51, 51));
        philhealthField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        philhealthField.setText("0");
        getContentPane().add(philhealthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 110, 30));

        label9.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        label9.setForeground(new java.awt.Color(51, 51, 51));
        label9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label9.setText("Days Worked:");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 100, 30));

        daysWorkedField.setEditable(false);
        daysWorkedField.setBackground(new java.awt.Color(204, 204, 204));
        daysWorkedField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        daysWorkedField.setForeground(new java.awt.Color(0, 102, 102));
        daysWorkedField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        daysWorkedField.setText("0 days");
        getContentPane().add(daysWorkedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 130, 30));

        backButton.setForeground(new java.awt.Color(0, 102, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 120, -1));

        label25.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label25.setForeground(new java.awt.Color(51, 51, 51));
        label25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label25.setText("Payslip Period");
        getContentPane().add(label25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 130, -1));

        payslipPeriodComboBox.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        getContentPane().add(payslipPeriodComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 230, 30));

        label4.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label4.setForeground(new java.awt.Color(51, 51, 51));
        label4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label4.setText("Monthly Rate");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 130, -1));

        monthlyRateField.setEditable(false);
        monthlyRateField.setBackground(new java.awt.Color(255, 255, 255));
        monthlyRateField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        monthlyRateField.setForeground(new java.awt.Color(51, 51, 51));
        monthlyRateField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        monthlyRateField.setText("0");
        getContentPane().add(monthlyRateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 230, 30));

        label7.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label7.setForeground(new java.awt.Color(51, 51, 51));
        label7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label7.setText("Hourly Rate");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 110, -1));

        hourlyRateField.setEditable(false);
        hourlyRateField.setBackground(new java.awt.Color(255, 255, 255));
        hourlyRateField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        hourlyRateField.setForeground(new java.awt.Color(51, 51, 51));
        hourlyRateField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        hourlyRateField.setText("0");
        hourlyRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyRateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hourlyRateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 110, 30));

        label5.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label5.setForeground(new java.awt.Color(51, 51, 51));
        label5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label5.setText("Hours Worked");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, -1));

        hoursWorkedField.setEditable(false);
        hoursWorkedField.setBackground(new java.awt.Color(255, 255, 255));
        hoursWorkedField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        hoursWorkedField.setForeground(new java.awt.Color(51, 51, 51));
        hoursWorkedField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        hoursWorkedField.setText("0");
        getContentPane().add(hoursWorkedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 110, 30));

        label6.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label6.setForeground(new java.awt.Color(51, 51, 51));
        label6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label6.setText("Overtime");
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 110, -1));

        overtimeField.setEditable(false);
        overtimeField.setBackground(new java.awt.Color(255, 255, 255));
        overtimeField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        overtimeField.setForeground(new java.awt.Color(51, 51, 51));
        overtimeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        overtimeField.setText("0");
        getContentPane().add(overtimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 110, 30));

        label10.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        label10.setForeground(new java.awt.Color(51, 51, 51));
        label10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label10.setText("Overtime Pay");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 100, -1));

        overtimePayField.setEditable(false);
        overtimePayField.setBackground(new java.awt.Color(255, 255, 255));
        overtimePayField.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        overtimePayField.setForeground(new java.awt.Color(51, 51, 51));
        overtimePayField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        overtimePayField.setText("0");
        getContentPane().add(overtimePayField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 110, 30));

        label11.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        label11.setForeground(new java.awt.Color(0, 102, 102));
        label11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        label11.setText("Gross Pay (Before Deductions)");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 230, -1));

        totalGrossIncomeField.setEditable(false);
        totalGrossIncomeField.setBackground(new java.awt.Color(255, 255, 255));
        totalGrossIncomeField.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        totalGrossIncomeField.setForeground(new java.awt.Color(51, 51, 51));
        totalGrossIncomeField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        totalGrossIncomeField.setText("0");
        getContentPane().add(totalGrossIncomeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 230, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/PayslipSummary.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void benefitsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benefitsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_benefitsFieldActionPerformed

    private void printPayslipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPayslipButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printPayslipButtonActionPerformed

    private void pagibigFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagibigFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagibigFieldActionPerformed

    private void totalBenefitsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBenefitsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBenefitsFieldActionPerformed

    private void totalDeductionsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDeductionsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDeductionsFieldActionPerformed

    private void clothingAllowanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clothingAllowanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clothingAllowanceFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void hourlyRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyRateFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageManagerPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageManagerPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageManagerPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageManagerPayslip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageManagerPayslip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDateChooser;
    private util.LightButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JTextField benefitsField;
    private javax.swing.JTextField clothingAllowanceField;
    private javax.swing.JTextField daysWorkedField;
    private javax.swing.JTextField deductionsField;
    private javax.swing.JTextField grossIncomeField;
    private javax.swing.JTextField hourlyRateField;
    private javax.swing.JTextField hoursWorkedField;
    private javax.swing.JLabel label;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label15;
    private javax.swing.JLabel label16;
    private javax.swing.JLabel label17;
    private javax.swing.JLabel label18;
    private javax.swing.JLabel label19;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label20;
    private javax.swing.JLabel label21;
    private javax.swing.JLabel label22;
    private javax.swing.JLabel label23;
    private javax.swing.JLabel label24;
    private javax.swing.JLabel label25;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JTextField monthlyRateField;
    private javax.swing.JTextField overtimeField;
    private javax.swing.JTextField overtimePayField;
    private javax.swing.JTextField pagibigField;
    private javax.swing.JComboBox<String> payslipPeriodComboBox;
    private javax.swing.JTextField philhealthField;
    private javax.swing.JTextField phoneAllowanceField;
    private util.LightButton printPayslipButton;
    private javax.swing.JTextField riceSubsidyField;
    private javax.swing.JTextField sssField;
    private javax.swing.JTextField takeHomePayField;
    private javax.swing.JTextField totalBenefitsField;
    private javax.swing.JTextField totalDeductionsField;
    private javax.swing.JTextField totalGrossIncomeField;
    private javax.swing.JTextField withholdingTaxField;
    // End of variables declaration//GEN-END:variables
}
